import 'dart:math';

class FunnyTasks {
  FunnyTasks._();

  static List<String> tasks = [
    'Take a candy out of the plate filled with flour by mouth',
    'Throw a raw egg to a friend',
    'Hop 20 times on one foot',
    'Shout "cuckoo" out a window five times',
    'Put the elbow of your right hand on your left knee',
    'Guess the food when blindfolded',
    'Make a paper aeroplane and hit a running friend with it',
    'Push a fruit or vegetable from one side of the table to the other without using your hands',
    'Drink two glasses of water',
    'Write any word on the paper, holding the pencil with your lips',
    'Guess the word your friend has in mind with three clues',
    'Say quickly without stuttering: "Give papa a cup of proper coffe in a copper coffe cup."',
    'Say quickly without stuttering: "Can you can a can as a canner can can a can?"',
    'Lick a lemon and don\'t grin',
    'Stir the sugar in the tea by clamping the spoon in your teeth',
    'Spin around 15 times and sit on any chair',
    'Put a pot on your head and sing a song',
    'Name any animal by the first and last letters of your name',
    'Fill your mouth with water and say, "hello everybody"',
    'Get on all fours and moo like a cow',
    'Set a the wrong time on any clock',
    'Pretend to be a burglar with your friend or relative by shouting: "Trick or treat?!"',
    'Pick up a torch, hold it to your face and laugh sinisterly',
    'Take any food in your mouth and say, "a golden cloud has fallen overnight on the chest of a giant cliff',
    'Take a pair of scissors and cut off a strand of hair',
    'Praise yourself 5 times',
    'Say 10 names',
    'Draw your best friend',
    'Draw a car with your left hand. if you are left-handed, use your right hand',
    'Sing a song like a hamster: inflate your cheeks and snap your fingers at them',
    'Hold your breath for 10 seconds',
    'Act three different emotions',
    'Make a loud cry',
    'Shout out the window: "Merry Christmas!"',
    'Take half of an apple (or other fruit) in your mouth and say, "Black background, brown background"',
    'Sit down 10 times',
    'Shout like a monkey: "uh-uh-uh"',
    'Be quiet for 1 minute. Your friends can force you to talk.',
    'Go to a mirror and say to yourself 10 times: "how beautiful I am!" without smiling',
    'Sit in the lotus pose for 2 minutes',
    'Build a house of cards (or other items)',
    'Pick up an item with your feet',
    'Flip a coin with one elbow and catch it with the other',
    'Guess a friend being blindfolded',
    'Close your eyes and open the SMS app in your phone',
    'Cry like a newborn baby',
    'Dance like a ballerina in a ballet show',
    'Dance without a song or a beat',
    'Demonstrate a six-feet tall woman/man entering a race car',
    'Demonstrate how to eat noodles with chopsticks',
    'Draw a table using a pen at one single go',
    'Draw the picture of your pet',
    'Hop to the door and back while pulling your two ears',
    'If you were to travel out of the country, where would you love to go? Tell us why',
    'Invent a new word and define it',
    'Jump and touch the ceiling',
    'Kiss every finger separately',
    'Kiss your feet',
    'Lick the tip of your elbow',
    'Call a random number on your phone',
    'Mention 5 objects you can find in the kitchen and tell what they are used for',
    'Mount two textbooks on your head and walk briskly around the room without losing balance',
    'Name the color of your socks without looking at them',
    'Place your foot over your head',
    'Place your leg on a friend\'s shoulder',
    'Pretend like you drunk after drinking vodka for the first time',
    'Pull off your sweater/glove and turn it inside out and put in on again',
    'Pull your right ear, tilt your neck to the right and walk sideways to your left at the same time',
    'Raise your right knee to your chin and count backward from 20 to 0',
    'Recite the alphabet backward',
    'Remove your shoelaces and use them to design a puppy on the floor',
    'Repeat “She sells seashells on the seashore’ with no mistakes',
    'Roughen up your bed and remake it',
    'Slap yourself in the face with both hands as many times as you can in 5 seconds',
    'Spell your name using body gestures',
    'Squat and jump 10 times nonstop',
    'Take off one sock',
    'Take off your right sock and wear it in your left palm',
    'Take off your socks off and wear them inside out',
    'Throw 20 imaginary punches at a boxing opponent, nonstop',
    'Touch the four corner edges in the room',
    'Touch your nose with your tongue',
    'Touch all the walls in the house',
    'What is the number before 1 trillion?',
    'Write down your name backward',
    'Name 20 foods',
    'Make 5 animal sounds',
    'Name 20 cities',
    'Roar like a lion and meow like a cat immediately afterward',
    'Act like you are walking through the Sahara Desert at extreme heat',
    'Act like you are walking at extreme cold',
    'Name 10 musicians',
    'Pick up a biscuit or a cookie from the table and eat it without using your hands',
    'Hit a ping-pong ball into a glass from a distance',
    'Make a ball of paper and hit the glass from a distance',
    'Draw your friend while blindfolded',
    'Act like an animal, and your friend needs to guess what it is',
    'Play rock paper scissors with a friend',
    'Pick up an apple or another fruit from a table without using your hands',
    'Try to watch a funny video or a series of videos without grinning, laughing, or breaking into a smile',
    'Act as if you are caught in heavy rain without an umbrella',
    'Recreate an emoji, and your friend needs to guess it',
    'Say a word backwards, and your friend needs to guess it',
  ];

  static String getRandomTask() {
    final random = new Random();
    final index = random.nextInt(tasks.length);
    return tasks[index];
  }
}
